name: Test SearXNG

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run deploy-searxng action
        uses: ./.github/actions/deploy-searxng
